{
  "name": "SemanticModel",
  "compatibilityLevel": 1500,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/bitsql wctc edu;MedicareReportingDW",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "bitsql.wctc.edu",
            "database": "MedicareReportingDW"
          },
          "authentication": null,
          "query": null
        },
        "options": {},
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "kind": "SQL",
          "path": "bitsql.wctc.edu;MedicareReportingDW",
          "Username": "MedicareReportingUser",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "Date",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "Date Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DateKey"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "Date"
          },
          {
            "name": "Day Of Month",
            "dataType": "int64",
            "sourceColumn": "DayOfMonth"
          },
          {
            "name": "Month Number",
            "dataType": "int64",
            "sourceColumn": "MonthNumber"
          },
          {
            "name": "Month Name",
            "dataType": "string",
            "sourceColumn": "MonthName"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year"
          },
          {
            "name": "Day Of Week Name",
            "dataType": "string",
            "sourceColumn": "DayOfWeekName"
          },
          {
            "name": "Day Of Week Number",
            "dataType": "int64",
            "sourceColumn": "DayOfWeekNumber"
          },
          {
            "name": "IsWeekend",
            "dataType": "boolean",
            "isHidden": true,
            "sourceColumn": "IsWeekend",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "type": "calculated",
            "name": "Month Description",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": " [Month Number]&\" - \"&[Month Name]"
          },
          {
            "type": "calculated",
            "name": "Day Of Week Description",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "[Day Of Week Number]&\" - \"&[Day Of Week Name]"
          },
          {
            "type": "calculated",
            "name": "Day Long Description",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": " [Day Of Week Name]&\", \"&[Month Name]&\" \"&[Day Of Month]&\", \"&[Year]"
          },
          {
            "type": "calculated",
            "name": "Is Weekend",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": " IF([IsWeekend],\"Weekend\",\"Weekday\")"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/bitsql wctc edu;MedicareReportingDW\",",
                "    FacilityMeasures_WI_DW_DimDate = Source{[Schema=\"FacilityMeasures_WI_DW\",Item=\"DimDate\"]}[Data],",
                "    #\"Sorted Rows\" = Table.Sort(FacilityMeasures_WI_DW_DimDate,{{\"Date\", Order.Descending}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Sorted Rows\", each [Date] <Date.From(DateTime.LocalNow()) and [Date] <> #date(1900, 1, 1)),",
                "    #\"Sorted Rows1\" = Table.Sort(#\"Filtered Rows\",{{\"Date\", Order.Ascending}})",
                "in",
                "    #\"Sorted Rows1\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Calendar",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year"
              },
              {
                "name": "Month Name",
                "ordinal": 1,
                "column": "Month Name"
              },
              {
                "name": "Day Of Week Name",
                "ordinal": 2,
                "column": "Day Of Week Name"
              },
              {
                "name": "Day Of Month",
                "ordinal": 3,
                "column": "Day Of Month"
              }
            ]
          }
        ]
      },
      {
        "name": "Facilities",
        "columns": [
          {
            "name": "Facility Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FacilityKey"
          },
          {
            "name": "Facility ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FacilityID"
          },
          {
            "name": "Facility Name",
            "dataType": "string",
            "sourceColumn": "FacilityName"
          },
          {
            "name": "Facility Address",
            "dataType": "string",
            "sourceColumn": "FacilityAddress"
          },
          {
            "name": "Facility City",
            "dataType": "string",
            "sourceColumn": "FacilityCity"
          },
          {
            "name": "Facility State",
            "dataType": "string",
            "sourceColumn": "FacilityState"
          },
          {
            "name": "Facility Zip Code",
            "dataType": "string",
            "sourceColumn": "FacilityZipCode"
          },
          {
            "name": "Facility County Name",
            "dataType": "string",
            "sourceColumn": "FacilityCountyName"
          },
          {
            "name": "Facility Phone Number",
            "dataType": "string",
            "sourceColumn": "FacilityPhoneNumber"
          },
          {
            "type": "calculated",
            "name": "Facility Full Address",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "[Facility Address]&\" \"&[Facility City]&\", \"&[Facility State]&\" \"&[Facility Zip Code]"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/bitsql wctc edu;MedicareReportingDW\",",
                "    FacilityMeasures_WI_DW_DimFacility = Source{[Schema=\"FacilityMeasures_WI_DW\",Item=\"DimFacility\"]}[Data]",
                "in",
                "    FacilityMeasures_WI_DW_DimFacility"
              ]
            }
          }
        ]
      },
      {
        "name": "Facility Scores",
        "columns": [
          {
            "name": "Measure Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MeasureKey"
          },
          {
            "name": "Measure ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MeasureID"
          },
          {
            "name": "Facility Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FacilityKey"
          },
          {
            "name": "Facility ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FacilityID"
          },
          {
            "name": "Facility Measure ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FacilityMeasureID"
          },
          {
            "name": "Measure Name",
            "dataType": "string",
            "sourceColumn": "MeasureName"
          },
          {
            "name": "Score Compared To National",
            "dataType": "string",
            "sourceColumn": "ScoreComparedToNational"
          },
          {
            "name": "Score",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Score"
          },
          {
            "name": "National Score High",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "NationalScoreHigh"
          },
          {
            "name": "National Score Low",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "NationalScoreLow"
          },
          {
            "name": "National Score Average",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "NationalScoreAverage"
          },
          {
            "name": "Measure Sort Order Name",
            "dataType": "string",
            "sourceColumn": "MeasureSortOrderName"
          },
          {
            "name": "Measure Type Name",
            "dataType": "string",
            "sourceColumn": "MeasureTypeName"
          },
          {
            "name": "Start Date",
            "dataType": "dateTime",
            "sourceColumn": "StartDate"
          },
          {
            "name": "End Date",
            "dataType": "dateTime",
            "sourceColumn": "EndDate"
          },
          {
            "name": "Start Date Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "StartDateKey"
          },
          {
            "name": "End Date Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "EndDateKey"
          },
          {
            "type": "calculated",
            "name": "Days Recorded",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "DATEDIFF([Start Date],[End Date],DAY)"
          },
          {
            "name": "Measure Sort Order Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MeasureSortOrderNumber"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/bitsql wctc edu;MedicareReportingDW\",",
                "    FacilityMeasures_WI_DW_FactMeasure = Source{[Schema=\"FacilityMeasures_WI_DW\",Item=\"FactMeasure\"]}[Data]",
                "in",
                "    FacilityMeasures_WI_DW_FactMeasure"
              ]
            }
          }
        ]
      },
      {
        "name": "Facility Scores Measures",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "col1",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[col1]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "DATATABLE(\"col1\",string,{{\"\"}})"
            }
          }
        ],
        "measures": [
          {
            "name": "WI High Score",
            "expression": "MAX('Facility Scores'[Score])"
          },
          {
            "name": "WI Low Score",
            "expression": "MIN('Facility Scores'[Score])"
          },
          {
            "name": "WI Average Score",
            "expression": "AVERAGE('Facility Scores'[Score])"
          },
          {
            "name": "Measure Score",
            "expression": "SUM('Facility Scores'[Score])"
          },
          {
            "name": "Measure Sort Number",
            "expression": "MAX('Facility Scores'[Measure Sort Order Number])"
          },
          {
            "name": "US High Score",
            "expression": "MAX('Facility Scores'[National Score High])"
          },
          {
            "name": "US Low Score",
            "expression": "MIN('Facility Scores'[National Score Low])"
          },
          {
            "name": "US Average Score",
            "expression": "Average('Facility Scores'[National Score Average])"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "9f2a833c-0410-43c7-a795-93946dc65894",
        "fromTable": "Facility Scores",
        "fromColumn": "End Date Key",
        "toTable": "Date",
        "toColumn": "Date Key",
        "isActive": false
      },
      {
        "name": "96fd7a28-33fb-4258-99ac-08a59017ee7a",
        "fromTable": "Facility Scores",
        "fromColumn": "Start Date Key",
        "toTable": "Date",
        "toColumn": "Date Key"
      },
      {
        "name": "47c5b8db-edb9-42fc-8424-862d5df98bd6",
        "fromTable": "Facility Scores",
        "fromColumn": "Facility Key",
        "toTable": "Facilities",
        "toColumn": "Facility Key"
      }
    ],
    "roles": [
      {
        "name": "Report User",
        "modelPermission": "read"
      },
      {
        "name": "Process Database",
        "modelPermission": "administrator"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "600"
      }
    ]
  },
  "id": "SemanticModel"
}